version: '3.7'

services:
  nemde:
    build:
      context: .
    volumes:
      - ./scripts/validation:/app/scripts/validation
      - ./nemde/tests:/app/nemde/tests
      - ./casefiles/zipped:/app/casefiles/zipped
    entrypoint: /app/scripts/entrypoint.sh
    depends_on:
      - mysql

# networks:
#   default:
#     external:
#       name: mysql_default

  mysql:
    image: kubedb/mysql:5.7.25
    command: --max_allowed_packet=32505856
    env_file:
      - ./mysql/.env
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/mysqlconf:/etc/mysql/conf.d
