version: '3.7'

services:
  nemde:
    build:
      context: .
    volumes:
      - ./scripts/validation:/app/scripts/validation
      - ./nemde/tests:/app/nemde/tests
    entrypoint: /app/scripts/entrypoint.sh
    environment:
      - ONLINE_FLAG=true