version: '3.7'

services:
  nemde:
    build:
      context: .
    volumes:
      - ./scripts/validation:/app/scripts/validation
    entrypoint: /app/scripts/entrypoint.sh
    environment:
      - ONLINE_FLAG=true