version: '3.7'

services:
  nemde:
    build:
      context: .
    volumes:
      - ./reports:/app/reports
      - ./casefiles/zipped:/app/casefiles/zipped
    entrypoint: /app/scripts/entrypoint.sh
    env_file:
      - ./config/default.env
    depends_on:
      - mysql

  mysql:
    image: kubedb/mysql:5.7.25
    command: --max_allowed_packet=32505856
    env_file:
      - ./mysql/.env
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/mysqlconf:/etc/mysql/conf.d
