version: '3.3'
services:
  db:
    image: kubedb/mysql:5.7.25
    restart: always
    env_file:
      - .env
    ports:
      - '3307:3306'
    expose:
      - '3307'
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./mysqlconf:/etc/mysql/conf.d
